#!/usr/local/projects/routing/help/html_filter.pl
When you view a patron's record, you will see the following fields (assuming your
account sufficient rights to at least view them):
<ul>
<li><a href="field_Staff_Name.cgi">Staffer name</a>
<li><a href="field_Staff_Distributor.cgi">Distributor</a>
<li><a href="field_Staff_Email.cgi">Email</a>
<li><a href="field_Staff_Phone.cgi">Phone</a>
<li><a href="field_Staff_Notify.cgi">Notify</a>
<li><a href="field_Staff_Address.cgi">Address</a>
<li><a href="field-Staff-Index_user.cgi">Index user</a>
<li><a href="field-Staff-Emergency_contact_0.cgi">First emergency contact</a>
<li><a href="field-Staff-Emergency_relationship_0.cgi">Relationship</a>
<li><a href="field-Staff-Emergency_phone_0.cgi">Phone</a>
<li><a href="field-Staff-Emergency_contact_1.cgi">Second emergency contact</a>
<li><a href="field-Staff-Emergency_relationship_1.cgi">Relationship</a>
<li><a href="field-Staff-Emergency_phone_1.cgi">Phone</a>
<li><a href="field-Staff-Preferred_hospital.cgi">Preferred hospital</a>
<li><a href="field-Staff-Maximum_patrons.cgi">Maximum patrons</a>
<li><a href="field-Staff-Weight_limit.cgi">Weight limit (kgs)</a>
<li><a href="field-Staff-Times_available.cgi">Times available</a>
</ul>
To modify fields you are allowed to modify, click on
<a href="button_Edit.cgi"><button>Edit</button></a>.  Once you have completed any changes,
click on <a href="button-Update.cgi"><button>Update</button></a>.

<p>If you want to add this new staff member to your personal contact list, click on
<a href="button_Download_contact.cgi"><button>Download contact</button></a>.

<p>Click
<a href="button_Download_invoices.cgi"><button>Download invoices</button></a>
to download pdf files of all the expense reports generated by this staff member.

<p>Click
<a href="button_Maps.cgi"><button>List maps</button></a>
to view maps of all the routes driven by this staff member.

<p>Click <a href="button_larr.cgi"><button>&larr;</button></a> to return to a higher menu.


