BASE=/var/log/routing/progress/MOW_Sagadahoc
FILES=										\
	$(BASE)/2025-04-30-Woolwich-Chris_Caldwell-1uA6to.po			\
	$(BASE)/2025-04-02-Brunswick_Towers-Chris_Caldwell-XXXXXX.po		\
	$(BASE)/2025-04-25-Bath_Washington_House-Chris_Caldwell-1u8J35.po

all:
	/var/www/routing/sto/index-test.cgi pomap $(FILES) /tmp/output.gpx
